stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - |
      ssh -p 2222 $DEPLOY_USER@$DEPLOY_HOST "
        cd /data/tpc-helpit &&
        git fetch origin &&
        git pull &&
        docker compose up -d --build
      "
  only:
    - main
  when: manual
